flowchart TB
    start["**START HERE**"] --> du["**Element: Duty**<br>Did D owe a<br>**legal duty** to P?"]
    du -- **No** --> not_liab["**STOP:<br>Not Liable**"]
    du -- **Yes** --> da["**Element: Damages**<br>Did P suffer **damages**<br>(aka harm, injury, loss)?"]
    da -- **No** --> not_liab
    da -- **Yes** --> br["**Element: Breach**<br>Did D **breach** their duty?"]
    br -- **No** --> not_liab
    br -- **Yes** --> ca@{ label: "**Element: Causation**<br>Did D's conduct<br>**cause** P's harm?" }
    ca -- **No** --> not_liab
    ca -- **Yes** --> pf(["**The D has a prima facie case for negligence**"])
    pf --> def["Does D have an<br>**affirmative defense**?"]
    def -- **No** --> liable{"**D is liable**"}
    def -- **Yes** --> not_liab

    start@{ shape: terminal}
    not_liab@{ shape: terminal}
    ca@{ shape: rect}

    classDef element stroke-width:1px, stroke-dasharray:none, fill:#f3f5ff
	class du,da,br,ca,pf,def element;
    style start stroke-width:2.5px,stroke-dasharray: 2,fill:#fafafa,stroke:#000000
    style not_liab stroke-width:2.5px,fill:#FFF8F8,stroke:#880101
    style pf stroke-width:2.5px,fill:#e1f5fe,stroke:#01579b
    style liable stroke-width:2.5px,fill:#ebf5eb,stroke:#2c5e36